---
version: 2

registries:
  dockerhub-registry:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_PASSWORD}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "dev"

  - package-ecosystem: docker
    directories:
      - "/alpine/**"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
    registries: ["dockerhub-registry"]
