---
name: 'Build Push python-alpine'

on:
  push:
    branches:
      - main
    paths:
      - 'alpine/Dockerfile.alpine-amd64'
      - 'alpine/Dockerfile.alpine-arm64'
      - 'alpine/docker-bake.hcl'
  workflow_dispatch:

env:
  DOCKER_IMAGE: python
  DOCKER_IMAGE_OS: alpine
  DOCKER_IMAGE_GROUP: dev
  AWS_DEFAULT_REGION: us-east-1
  AWS_ECR_URI: public.ecr.aws/w2u0w5i6
  AWS_OIDC_ROLE_ARN: ${{secrets.AWS_OIDC_ROLE_ARN}}

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    strategy:
      matrix:
        architecture: [amd64, arm64]
        include:
          - architecture: amd64
            runner: ubuntu-latest
          - architecture: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{matrix.runner}}
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'set shell options globally'
        run: set -euxo pipefail

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'configure aws credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{env.AWS_OIDC_ROLE_ARN}}"
          role-session-name: "aws-oidc-${{github.repository.name}}-${{github.run_id}}"
          aws-region: "${{env.AWS_DEFAULT_REGION}}"

      - name: 'login to amazon ecr public'
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          DOCKER_IMAGE_TAG="$(cat ./${{env.DOCKER_IMAGE_OS}}/VERSION)"
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}" >> ${GITHUB_ENV}
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}"
          SYSTEM_CPU_PROC="$(grep -c ^proc /proc/cpuinfo)"
          echo "SYSTEM_CPU_PROC=${SYSTEM_CPU_PROC}" >> ${GITHUB_ENV}
          echo "SYSTEM_CPU_PROC=${SYSTEM_CPU_PROC}"

      - name: 'create ecr-public repository'
        run: |
          aws ecr-public create-repository --repository-name "${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}" --region "${{env.AWS_DEFAULT_REGION}}" || true

      - name: "build-${{matrix.architecture}}"
        uses: docker/bake-action@v5
        with:
          targets: "build-${{matrix.architecture}}"
          workdir: "./${{env.DOCKER_IMAGE_OS}}"

      - name: "push-${{matrix.architecture}}"
        run: docker push ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-${{matrix.architecture}}

  create-manifest:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'set shell options globally'
        run: set -euxo pipefail

      - name: 'configure aws credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{env.AWS_OIDC_ROLE_ARN}}"
          role-session-name: "aws-oidc-${{github.repository.name}}-${{github.run_id}}"
          aws-region: "${{env.AWS_DEFAULT_REGION}}"

      - name: 'login to amazon ecr public'
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          DOCKER_IMAGE_TAG="$(cat ./${{env.DOCKER_IMAGE_OS}}/VERSION)"
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG#v}"

      - name: 'create docker manifest final'
        run: |
          docker manifest create ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}} \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-amd64 \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-arm64
          docker manifest annotate ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}} \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-amd64 --arch amd64
          docker manifest annotate ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}} \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-arm64 --arch arm64
          docker manifest push ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}

          docker manifest create ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:latest \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-amd64 \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-arm64
          docker manifest annotate ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}} \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-amd64 --arch amd64
          docker manifest annotate ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}} \
            ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:${{env.DOCKER_IMAGE_TAG}}-arm64 --arch arm64
          docker manifest push ${{env.AWS_ECR_URI}}/${{env.DOCKER_IMAGE_GROUP}}/${{env.DOCKER_IMAGE}}:latest
